#ログイン画面
LOGIN_URL: "https://toamas-amusement.thincacloud.com/Logon"
# 要素待機タイムアウト（秒）
WAIT_SEC: 30  

BASE_URL: "https://toamas-amusement.thincacloud.com"

DATE_FROM: "2026-04-13 03:00"

DATE_TO: "2026-04-19 23:59"
